### ISSUE TITLE
Registration end-point update

### ISSUE THREAD

**Issue by ghost** [Bartoloni00/aragoge-backend#1]
You could update the way the message is sent when the mail is already registered in the registration end-point, it would help me to return "errors" like those of password
[Grabación de pantalla desde 2024-09-25 21-40-10.webm](https://github.com/user-attachments/assets/1e043394-d754-4921-ad1b-2d5099ab6bb7)

**Comment by Bartoloni00** [comment]
Thanks for reporting that normalization error. I will fix that issue in the next commit.

**Comment by ghost** [comment]
Thank you for your prompt response, from the frontend we thank you
