### ISSUE TITLE
Adding folders for images

### ISSUE THREAD

**Issue by ghost** [Bartoloni00/aragoge-backend#2]
![Captura de pantalla 2024-11-28 115154](https://github.com/user-attachments/assets/403735f0-9f0d-472f-86a4-c423c539519c)

4. Creación de las carpetas plannings y users dentro de:
``` Bash
    cd storage/app/public
    mkdir plannings
    mkdir users
```
> [!IMPORTANT]
>
> En caso de no existir las carpetas mencionadas realizar este paso

**Comment by Bartoloni00** [comment]
En breve añadire eso junto a los endpoints solicitados

**Comment by ghost** [comment]
Nos interesa
